service: sls-dev-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'develop'}
  region: ${opt:region, 'us-east-1'}
  apiName: sls-dev-api

plugins:
  - serverless-offline

functions:
  health-check:
    handler: routes/healthCheckRoutes.handler
    name: sls-dev-api-health-check
    events:
      - http:
          method: GET
          path: /health-check
          cors: true